[package]
name = "sfst"
version = "0.1.0"
edition = "2024"

[dependencies]
clap = { version = "4.0", features = ["derive"] }

[build-dependencies]
cc = "1.0"

[[bin]]
name = "main"
path = "src/main.rs"

[lib]
name = "sfst"
crate-type = ["cdylib", "rlib"]
